from enum import Enum, IntEnum


class BinanceTransferTypeEnum(str, Enum):
    MAIN_C2C = "MAIN_C2C"
    MAIN_UMFUTURE = "MAIN_UMFUTURE"
    MAIN_CMFUTURE = "MAIN_CMFUTURE"
    MAIN_MARGIN = "MAIN_MARGIN"
    MAIN_MINING = "MAIN_MINING"
    C2C_MAIN = "C2C_MAIN"
    C2C_UMFUTURE = "C2C_UMFUTURE"
    C2C_MINING = "C2C_MINING"
    C2C_MARGIN = "C2C_MARGIN"
    UMFUTURE_MAIN = "UMFUTURE_MAIN"
    UMFUTURE_C2C = "UMFUTURE_C2C"
    UMFUTURE_MARGIN = "UMFUTURE_MARGIN"
    CMFUTURE_MAIN = "CMFUTURE_MAIN"
    CMFUTURE_MARGIN = "CMFUTURE_MARGIN"
    MARGIN_MAIN = "MARGIN_MAIN"
    MARGIN_UMFUTURE = "MARGIN_UMFUTURE"
    MARGIN_CMFUTURE = "MARGIN_CMFUTURE"
    MARGIN_MINING = "MARGIN_MINING"
    MARGIN_C2C = "MARGIN_C2C"
    MINING_MAIN = "MINING_MAIN"
    MINING_UMFUTURE = "MINING_UMFUTURE"
    MINING_C2C = "MINING_C2C"
    MINING_MARGIN = "MINING_MARGIN"
    MAIN_PAY = "MAIN_PAY"
    PAY_MAIN = "PAY_MAIN"
    ISOLATEDMARGIN_MARGIN = "ISOLATEDMARGIN_MARGIN"
    MARGIN_ISOLATEDMARGIN = "MARGIN_ISOLATEDMARGIN"
    ISOLATEDMARGIN_ISOLATEDMARGIN = "ISOLATEDMARGIN_ISOLATEDMARGIN"


class BinanceFiatMovementEnum(IntEnum):
    DEPOSIT = 0
    WITHDRAW = 1


class BinanceFiatPaymentsEnum(IntEnum):
    BUY = 0
    SELL = 1
